const QuestTaskConfigType = Object.freeze({
    STREAM_ON_DESKTOP: 'STREAM_ON_DESKTOP',
    PLAY_ON_DESKTOP: 'PLAY_ON_DESKTOP',
    PLAY_ON_DESKTOP_V2: 'PLAY_ON_DESKTOP_V2',
    PLAY_ON_XBOX: 'PLAY_ON_XBOX',
    PLAY_ON_PLAYSTATION: 'PLAY_ON_PLAYSTATION',
    WATCH_VIDEO: 'WATCH_VIDEO',
    WATCH_VIDEO_ON_MOBILE: 'WATCH_VIDEO_ON_MOBILE',
    PLAY_ACTIVITY: 'PLAY_ACTIVITY',
    ACHIEVEMENT_IN_GAME: 'ACHIEVEMENT_IN_GAME',
    ACHIEVEMENT_IN_ACTIVITY: 'ACHIEVEMENT_IN_ACTIVITY'
});

module.exports = {
    QuestTaskConfigType
};
